<?php

require_once 'core/controller.php';
require_once 'core/helpers/patterns.php';
require_once 'core/helpers/template.php';

class VerController extends Controller {

   // 20230801 Cargar pagina
   function menu() {
		// verifica pagina a cargar, sino carga por defecto pagina principal
		$dataRequest["page"] = $_GET["page"] != null ? $_GET["page"] : 'login';
		if($dataRequest["page"] == "login"){
			$this->cargarLogin();
		}else if($dataRequest["page"] == "cpanelpvta"){
			$this->cargarPanelPrincipal();
		}
   }

   function cargarLogin() {
		//$dicc1 = array( SITEADM_HTML_TAG_COMMONHEAD	=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONHEAD );
		$dicc2 = array( SITEPVTA_HTML_TAG_SITETITLE			=> SITEPVTA_HTML_DES_SITETITLE,
						SITEPVTA_HTML_TAG_SITEDESCRIP		=> SITEPVTA_HTML_DES_SITEDESCRIP,
						SITEPVTA_HTML_TAG_SITEKEYWORDS		=> SITEPVTA_HTML_DES_SITEKEYWORDS,
						SITEPVTA_HTML_TAG_FAVICON			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_HTML_DIR_FAVICON,	
						SITEPVTA_CSS_TAG_LIB_BOOTSTRAP		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_BOOTSTRAP,
						SITEPVTA_CSS_TAG_LIB_FONTAWESOME	=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_FONTAWESOME,
						/*SITEADM_CSS_TAG_LIB_JQUERY_UI	=> SITEPVTA_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_JQUERY_UI,*/
						SITEPVTA_CSS_TAG_LIB_RESET			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_RESET,
						SITEPVTA_HTML_TAG_LOGO				=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_HTML_DIR_LOGO,
						SITEPVTA_JS_TAG_LIB_JQUERY			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_JQUERY,		  		
						/*SITEADM_JS_TAG_LIB_JQUERY_UI		=> SITEPVTA_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY_UI,*/
						SITEPVTA_JS_TAG_LIB_BSTRAP_JQ		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_BSTRAP_JQ,
						SITEPVTA_JS_TAG_LIB_BOOTSTRAP		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_BOOTSTRAP,
						SITEPVTA_JS_TAG_LIB_WITPERPVTA		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_WITPERPVTA,
						SITEPVTA_PATH_TAG_LARGE				=> SITEPVTA_PATH_DIR_LARGE,
						SITEPVTA_HTML_TAG_COPYRIGHT			=> SITEPVTA_HTML_DES_COPYRIGHT				
					);

		// ruta de pagina html
		$file = SITEPVTA_HTML_DIR_LOGIN;
		$html = file_get_contents($file);

		// Recorre la vistas a mostrar en el template
		/*foreach($dicc1 as $clave => $valor){
			$html = str_replace('{'. $clave .'}', file_get_contents($valor), $html);
		}*/

		$tmpl = new Template($html);
		print $tmpl->render($dicc2);
	}

	function cargarPanelPrincipal() {
		$dicc1 = array( 
				SITEPVTA_HTML_TAG_COMMONHEAD		=> SITEPVTA_HTML_DIR_COMMONHEAD,
				SITEPVTA_HTML_TAG_COMMONHEADER		=> SITEPVTA_HTML_DIR_COMMONHEADER,
				SITEPVTA_HTML_TAG_COMMONSIDEMENU	=> SITEPVTA_HTML_DIR_COMMONSIDEMENU,
				SITEPVTA_HTML_TAG_COMMONFOOTER		=> SITEPVTA_HTML_DIR_COMMONFOOTER
				);

		$dicc2 = array( SITEPVTA_HTML_TAG_SITETITLE			=> SITEPVTA_HTML_DES_SITETITLE,
				SITEPVTA_HTML_TAG_SITEDESCRIP		=> SITEPVTA_HTML_DES_SITEDESCRIP,
				SITEPVTA_HTML_TAG_SITEKEYWORDS		=> SITEPVTA_HTML_DES_SITEKEYWORDS,
				SITEPVTA_HTML_TAG_FAVICON			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_HTML_DIR_FAVICON,	
				SITEPVTA_CSS_TAG_LIB_BOOTSTRAP		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_BOOTSTRAP,
				SITEPVTA_CSS_TAG_LIB_FONTAWESOME	=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_FONTAWESOME,
				/*SITEADM_CSS_TAG_LIB_JQUERY_UI	=> SITEPVTA_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_JQUERY_UI,*/
				SITEPVTA_CSS_TAG_LIB_RESET			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_CSS_DIR_LIB_RESET,
				SITEPVTA_HTML_TAG_LOGO				=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_HTML_DIR_LOGO,
				SITEPVTA_JS_TAG_LIB_JQUERY			=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_JQUERY,		  		
				/*SITEADM_JS_TAG_LIB_JQUERY_UI		=> SITEPVTA_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY_UI,*/
				SITEPVTA_JS_TAG_LIB_BSTRAP_JQ		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_BSTRAP_JQ,
				SITEPVTA_JS_TAG_LIB_BOOTSTRAP		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_BOOTSTRAP,
				SITEPVTA_JS_TAG_LIB_WITPERPVTA		=> SITEPVTA_PATH_DIR_LARGE . SITEPVTA_JS_DIR_LIB_WITPERPVTA,
				SITEPVTA_PATH_TAG_LARGE				=> SITEPVTA_PATH_DIR_LARGE,
				SITEPVTA_HTML_TAG_COPYRIGHT			=> SITEPVTA_HTML_DES_COPYRIGHT				
			);

		// ruta de pagina html
		$file = SITEPVTA_HTML_DIR_PRINCIPAL;
		$html = file_get_contents($file);

	    // Recorre la vistas a mostrar en el template
	    foreach($dicc1 as $clave => $valor){
			$html = str_replace('{'. $clave .'}', file_get_contents($valor), $html);
	    }

		$tmpl = new Template($html);
		print $tmpl->render($dicc2); 
	}

}

?>
