<?php

require_once 'core/controller.php';
require_once 'core/helpers/patterns.php';
require_once 'core/helpers/template.php';

class VerController extends Controller {

   // 20210125 Cargar pagina
   function menu() {
		// verifica pagina a cargar, sino carga por defecto pagina principal
		$dataRequest["page"] = $_GET["page"] != null ? $_GET["page"] : 'login';
		if($dataRequest["page"] == "login"){
			$this->cargarLogin();
		}else if($dataRequest["page"] == "cpaneladmin"){
			$this->cargarPanelPrincipal();
		}
   }

   function cargarLogin() {
		//$dicc1 = array( SITEADM_HTML_TAG_COMMONHEAD	=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONHEAD );

		$dicc2 = array( SITEADM_HTML_TAG_SITETITLE		=> SITEADM_HTML_DES_SITETITLE,
						SITEADM_HTML_TAG_SITEDESCRIP	=> SITEADM_HTML_DES_SITEDESCRIP,
						SITEADM_HTML_TAG_SITEKEYWORDS	=> SITEADM_HTML_DES_SITEKEYWORDS,
						SITEADM_HTML_TAG_FAVICON		=> SITEADM_PATH_DIR_LARGE . SITEADM_HTML_DIR_FAVICON,	
						SITEADM_CSS_TAG_LIB_BOOTSTRAP	=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_BOOTSTRAP,
						SITEADM_CSS_TAG_LIB_FONTAWESOME	=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_FONTAWESOME,
						/*SITEADM_CSS_TAG_LIB_JQUERY_UI	=> SITECLI_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_JQUERY_UI,*/
						SITEADM_CSS_TAG_LIB_RESET		=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_RESET,
						SITEADM_HTML_TAG_LOGO			=> SITEADM_PATH_DIR_LARGE . SITEADM_HTML_DIR_LOGO,
						SITEADM_JS_TAG_LIB_JQUERY		=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY,		  		
						/*SITEADM_JS_TAG_LIB_JQUERY_UI	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY_UI,*/
						SITEADM_JS_TAG_LIB_BSTRAP_JQ	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_BSTRAP_JQ,
						SITEADM_JS_TAG_LIB_BOOTSTRAP	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_BOOTSTRAP,
						SITEADM_JS_TAG_LIB_WITPER_ADM	=> SITEADM_PATH_DIR_LARGE . SITEPADM_JS_DIR_LIB_WITPERPADM,
						SITEADM_PATH_TAG_LARGE			=> SITEADM_PATH_DIR_LARGE,
						SITEADM_HTML_TAG_COPYRIGHT		=> SITEADM_HTML_DES_COPYRIGHT				
					);

		// ruta de pagina html
		//$file = SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_LOGIN;
		$file = SITEADM_HTML_DIR_LOGIN;
		$html = file_get_contents($file);

		// Recorre la vistas a mostrar en el template
		/*foreach($dicc1 as $clave => $valor){
			$html = str_replace('{'. $clave .'}', file_get_contents($valor), $html);
		}*/

		$tmpl = new Template($html);
		print $tmpl->render($dicc2);
	}

	function cargarPanelPrincipal() {
		/*$dicc1 = array( 
				SITEADM_HTML_TAG_COMMONHEAD		=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONHEAD,
				SITEADM_HTML_TAG_COMMONHEADER	=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONHEADER,
				SITEADM_HTML_TAG_COMMONSIDEMENU	=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONSIDEMENU,
				SITEADM_HTML_TAG_COMMONFOOTER	=> SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_COMMONFOOTER
		    	     );*/
				
		$dicc1 = array( 
				SITEADM_HTML_TAG_COMMONHEAD		=> SITEADM_HTML_DIR_COMMONHEAD,
				SITEADM_HTML_TAG_COMMONHEADER	=> SITEADM_HTML_DIR_COMMONHEADER,
				SITEADM_HTML_TAG_COMMONSIDEMENU	=> SITEADM_HTML_DIR_COMMONSIDEMENU,
				SITEADM_HTML_TAG_COMMONFOOTER	=> SITEADM_HTML_DIR_COMMONFOOTER
				);

		$dicc2 = array( SITEADM_HTML_TAG_SITETITLE	=> SITEADM_HTML_DES_SITETITLE,
				SITEADM_HTML_TAG_SITEDESCRIP	=> SITEADM_HTML_DES_SITEDESCRIP,
				SITEADM_HTML_TAG_SITEKEYWORDS	=> SITEADM_HTML_DES_SITEKEYWORDS,
				SITEADM_HTML_TAG_FAVICON		=> SITEADM_PATH_DIR_LARGE . SITEADM_HTML_DIR_FAVICON,	
				SITEADM_CSS_TAG_LIB_BOOTSTRAP	=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_BOOTSTRAP,
				SITEADM_CSS_TAG_LIB_FONTAWESOME	=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_FONTAWESOME,
				/*SITEADM_CSS_TAG_LIB_JQUERY_UI	=> SITECLI_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_JQUERY_UI,*/
				SITEADM_CSS_TAG_LIB_RESET		=> SITEADM_PATH_DIR_LARGE . SITEADM_CSS_DIR_LIB_RESET,
				SITEADM_HTML_TAG_LOGO			=> SITEADM_PATH_DIR_LARGE . SITEADM_HTML_DIR_LOGO,
				SITEADM_JS_TAG_LIB_JQUERY		=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY,		  		
				/*SITEADM_JS_TAG_LIB_JQUERY_UI	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_JQUERY_UI,*/
				SITEADM_JS_TAG_LIB_BSTRAP_JQ	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_BSTRAP_JQ,
				SITEADM_JS_TAG_LIB_BOOTSTRAP	=> SITEADM_PATH_DIR_LARGE . SITEADM_JS_DIR_LIB_BOOTSTRAP,
				SITEADM_JS_TAG_LIB_WITPER_ADM	=> SITEADM_PATH_DIR_LARGE . SITEPADM_JS_DIR_LIB_WITPERPADM,
				SITEADM_PATH_TAG_LARGE			=> SITEADM_PATH_DIR_LARGE,
				SITEADM_HTML_TAG_COPYRIGHT		=> SITEADM_HTML_DES_COPYRIGHT
		    	     );

		// ruta de pagina html
		//$file = SITEADM_PATH_DIR_MEDIUM . SITEADM_HTML_DIR_PRINCIPAL;
		$file = SITEADM_HTML_DIR_PRINCIPAL;
		$html = file_get_contents($file);

	    // Recorre la vistas a mostrar en el template
	    foreach($dicc1 as $clave => $valor){
			$html = str_replace('{'. $clave .'}', file_get_contents($valor), $html);
	    }

		$tmpl = new Template($html);
		print $tmpl->render($dicc2); 
	}

}

?>
